[package]
name = "vole-itH-folding"
version = "0.1.0"
edition = "2021"

[patch.crates-io]
ark-r1cs-std = { git = "https://github.com/yelhousni/r1cs-std", rev = "440ca3" } # "perf/sw" branch

[profile.release]
debug = true
lto = true

[dependencies]
# Swanky family;
schmivitz = { git = "https://github.com/adust09/swanky", rev="c00e2b2de6db361c4108dcc03bfa5906c08ee59e"}
mac-n-cheese-sieve-parser = { git = "https://github.com/adust09/swanky",rev = "c00e2b2de6db361c4108dcc03bfa5906c08ee59e"}
swanky-field = { git = "https://github.com/adust09/swanky",rev = "c00e2b2de6db361c4108dcc03bfa5906c08ee59e"}
swanky-field-binary = { git = "https://github.com/adust09/swanky",rev = "c00e2b2de6db361c4108dcc03bfa5906c08ee59e"}
# This is the main library for the project.
folding-schemes = { git = "https://github.com/privacy-scaling-explorations/sonobe", package = "folding-schemes" }
solidity-verifiers = { git = "https://github.com/privacy-scaling-explorations/sonobe", package = "solidity-verifiers"}
# Arkworks family;
ark-bn254 = "^0.5.0"
ark-ff = "^0.5.0"
ark-r1cs-std = "^0.5.0"
ark-relations =  "^0.5.0"
ark-bls12-381 = "^0.5.0"
ark-crypto-primitives="^0.5.0"
ark-grumpkin="^0.5.0"
eyre = "0.6.12"
tempfile = "3.14.0"
rand = "0.8.5"
merlin = "3.0.0"
# This allows the crate to be built when targeting WASM.
# See more at: https://docs.rs/getrandom/#webassembly-support 
[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasmer = { version = "5.0.4", features = ["js"] }
