[package]
name = "vole"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
lto = true

[dependencies]
# folding-schemes = { git = "https://github.com/privacy-scaling-explorations/sonobe", package = "folding-schemes"}
# solidity-verifiers = { git = "https://github.com/privacy-scaling-explorations/sonobe", package = "solidity-verifiers"}
schmivitz = { git = "https://github.com/GaloisInc/swanky", rev = "cd3862acd39631cfc463f977028d792f9fb757d8"}
mac-n-cheese = { git = "https://github.com/GaloisInc/swanky", rev = "cd3862acd39631cfc463f977028d792f9fb757d8"}

# Arkworks family
# ark-bn254 = { version = "^0.5.0", default-features = false }
# ark-circom = { git = "https://github.com/winderica/circom-compat", branch = "arkworks-next", default-features = false }
# ark-crypto-primitives = { version = "^0.5.0", default-features = false }
# ark-ec = { version = "^0.5.0", default-features = false }
# ark-ff = { version = "^0.5.0", default-features = false }
# ark-groth16 = { version = "^0.5.0" }
# ark-grumpkin = { version = "^0.5.0", default-features = false }
# ark-mnt4-298 = { version = "^0.5.0" }
# ark-mnt6-298 = { version = "^0.5.0" }
# ark-pallas = { version = "^0.5.0" }
# ark-poly = { version = "^0.5.0", default-features = false }
# ark-poly-commit = { version = "^0.5.0" }
# ark-r1cs-std = { version = "^0.5.0", default-features = false }
# ark-relations = { version = "^0.5.0", default-features = false }
# ark-serialize = { version = "^0.5.0" }
# ark-snark = { version = "^0.5.0", default-features = false }
# ark-std = { version = "^0.5.0", default-features = false }
# ark-vesta = { version = "^0.5.0" }

# This allows the crate to be built when targeting WASM.
# See more at: https://docs.rs/getrandom/#webassembly-support 
[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[[example]]
name = "sha256"
path = "../examples/sha256.rs"
